config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all

  end

  def new
    @task = Task.new
  end

  def create
    newtask = Task.new(task_params)
    newtask.save
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "back to list", tasks_path %>

app/views/tasks/index.html.erb
<%= 'YOUR TASKS' %>

<ul>
  <% @tasks.each do |task| %>
  <li id="tasks"><input type="checkbox" class="form-check-input" id="exampleCheck1" <%= "checked" if task.completed %> > <%= link_to "#{task.title}", task_path(task.id)%>
    <div class="poubelle">
    <%= link_to task_path(task),
      method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
      </div>
  </li

<% end %>
</ul>

<%= link_to "add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" class="form-control" placeholder="Title">

  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Details</label>
    <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Details">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
 -->

 <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "back to list", tasks_path %>

app/views/tasks/show.html.erb
    <%= @task.title%>
    <%= @task.details%>
    <% if @task.completed = true %>
      <input type="checkbox" class="custom-control-input" id="defaultUnchecked">
      <label class="custom-control-label" for="defaultUnchecked">This task is completed yet!</label>
     <% end %>


<%= link_to "edit", edit_task_path %>
<div class="back"><%= link_to "back to list", tasks_path %>
</div>